# Generated by Django 5.0.9 on 2025-02-28 13:41

import django.db.models.deletion
import django_ckeditor_5.fields
import managerdashboard.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ids', models.CharField(default=managerdashboard.models.generate_unique_id, editable=False, max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=20)),
                ('desc', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text')),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exchng_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_type', models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20, null=True)),
                ('fee_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fee_fixed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('test_mode', models.BooleanField(default=False)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='payment_icons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateways',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('api_url', models.URLField()),
                ('api_key', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ids', models.CharField(default=managerdashboard.models.generate_unique_id, editable=False, max_length=32, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('sort', models.PositiveIntegerField(editable=False)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True, default='')),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
                'db_table': 'categories',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='ProviderTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='managerdashboard.provider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ids', models.CharField(default=managerdashboard.models.generate_unique_id, editable=False, max_length=32, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('api_provider_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('desc', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('original_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
                ('add_type', models.CharField(choices=[('manual', 'Manual'), ('api', 'API')], default='manual', max_length=6)),
                ('type', models.CharField(default='default', max_length=100)),
                ('api_service_id', models.CharField(blank=True, max_length=200, null=True)),
                ('dripfeed', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('cate_id', models.ForeignKey(db_column='cate_id', on_delete=django.db.models.deletion.PROTECT, related_name='services', to='managerdashboard.servicecategory')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'services',
                'ordering': ['cate_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ids', models.CharField(default=managerdashboard.models.generate_unique_id, editable=False, max_length=32, unique=True)),
                ('type', models.CharField(choices=[('direct', 'direct'), ('api', 'api')], default='direct', max_length=10)),
                ('main_order_id', models.IntegerField(blank=True, null=True)),
                ('service_type', models.CharField(blank=True, default='default', max_length=50, null=True)),
                ('api_provider_id', models.IntegerField(blank=True, null=True)),
                ('api_service_id', models.CharField(blank=True, max_length=200, null=True)),
                ('api_order_id', models.IntegerField(blank=True, default=0, null=True)),
                ('link', models.CharField(blank=True, max_length=191, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('usernames', models.TextField(blank=True, null=True)),
                ('username', models.TextField(blank=True, null=True)),
                ('hashtags', models.TextField(blank=True, null=True)),
                ('hashtag', models.TextField(blank=True, null=True)),
                ('media', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('sub_posts', models.IntegerField(blank=True, null=True)),
                ('sub_min', models.IntegerField(blank=True, null=True)),
                ('sub_max', models.IntegerField(blank=True, null=True)),
                ('sub_delay', models.IntegerField(blank=True, null=True)),
                ('sub_expiry', models.TextField(blank=True, null=True)),
                ('sub_response_orders', models.TextField(blank=True, null=True)),
                ('sub_response_posts', models.TextField(blank=True, null=True)),
                ('sub_status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Paused', 'Paused'), ('Completed', 'Completed'), ('Expired', 'Expired'), ('Canceled', 'Canceled')], max_length=10, null=True)),
                ('charge', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('completed', 'completed'), ('processing', 'processing'), ('inprogress', 'inprogress'), ('pending', 'pending'), ('partial', 'partial'), ('refunded', 'refunded'), ('canceled', 'canceled')], default='pending', max_length=10)),
                ('start_counter', models.CharField(default='0', max_length=191)),
                ('remains', models.CharField(default='0', max_length=191)),
                ('is_drip_feed', models.BooleanField(default=False)),
                ('runs', models.IntegerField(default=0)),
                ('interval', models.IntegerField(default=0)),
                ('dripfeed_quantity', models.CharField(default='0', max_length=191)),
                ('note', models.TextField(blank=True, null=True)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('uid', models.ForeignKey(blank=True, db_column='uid', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='uid')),
                ('service_id', models.ForeignKey(blank=True, db_column='service_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='managerdashboard.service', to_field='ids')),
                ('cate_id', models.ForeignKey(blank=True, db_column='cate_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='managerdashboard.servicecategory')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='ServiceUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('new_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('old_min', models.IntegerField()),
                ('new_min', models.IntegerField()),
                ('old_max', models.IntegerField()),
                ('new_max', models.IntegerField()),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='managerdashboard.service')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='waiting', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managerdashboard.paymentmethod')),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='uid')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created'],
            },
        ),
    ]
