# Generated by Django 5.0.9 on 2025-02-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerdashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='ids',
            field=models.CharField(default='db01de551abb4133b59d3e4a20b35896', editable=False, max_length=32, unique=True),
        ),
    ]
