# Generated by Django 5.0.9 on 2025-02-28 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerdashboard', '0002_alter_service_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='ids',
            field=models.CharField(default='ee58dd8e992c4217a7f5b1841e95e2f7', editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='uid',
            field=models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='uid'),
        ),
    ]
