# Generated by Django 5.1 on 2024-11-09 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managerdashboard', '0002_provider_providertransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='currency',
        ),
    ]
