# Generated by Django 5.1 on 2024-11-09 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managerdashboard', '0007_alter_service_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='service',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='managerdashboard.provider'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
