# Generated by Django 5.0.9 on 2025-02-26 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_user_phone_number_remove_user_profile_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='history_jp',
            new_name='history_ip',
        ),
    ]
