# Generated by Django 5.0.9 on 2025-02-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('pro-access', 'Pro Access'), ('silver-member', 'Silver Member'), ('gold-elite', 'Gold Elite'), ('platinum-status', 'Platinum Status'), ('diamond-master', 'Diamond Master'), ('ultimate-legend', 'Ultimate Legend')], default='pro-access', max_length=15),
        ),
    ]
