# Generated by Django 5.0.9 on 2025-02-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('Silver Member', 'Silver Member'), ('Gold Elite', 'Gold Elite'), ('Platinum Status', 'Platinum Status'), ('Diamond Master', 'Diamond Master'), ('Ultimate Legend', 'Ultimate Legend')], default='silver-member', max_length=15),
        ),
    ]
