# Generated by Django 5.0.9 on 2025-02-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('silver-member', 'Silver Member'), ('gold-elite', 'Gold Elite'), ('platinum-status', 'Platinum Status'), ('diamond-master', 'Diamond Master'), ('ultimate-legend', 'Ultimate Legend')], default='silver-member', max_length=15),
        ),
    ]
