# Generated by Django 5.0.9 on 2025-02-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.UUIDField(default=34354534, unique=True),
            preserve_default=False,
        ),
    ]
