# Generated by Django 5.1 on 2024-11-09 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0002_alter_ticket_options_rename_message_ticket_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='updated_at',
            new_name='changed',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ids',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='uid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='tickets',
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('is_read', models.BooleanField(default=False)),
                ('uid', models.IntegerField(blank=True, null=True)),
                ('ids', models.CharField(blank=True, max_length=255, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='user_dashboard.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ticket_messages',
                'ordering': ['created'],
            },
        ),
        migrations.DeleteModel(
            name='TicketReply',
        ),
    ]
